services:
  main-db:
    image: postgres:17-alpine
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  redis:
    image: redis:7.2.5-alpine
    restart: always
    ports:
      - "${REDIS_PORT}:6379"
  p3x-redis-ui:
    image: patrikx3/p3x-redis-ui:2024.10.106
    ports:
      - 7843:7843
    environment:
      REDIS_HOST: "redis"
      REDIS_PORT: ${REDIS_PORT}
    volumes:
      - redis_ui_data:/settings
  pgadmin4:
    image: dcagatay/pwless-pgadmin4:8.12
    ports:
      - 5050:80
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_HOST: "main-db"
      POSTGRES_PORT: ${DB_PORT}
      POSTGRES_DB: ${DB_DATABASE}

volumes:
  db_data:
  redis_ui_data:
